export const names = ["Fondue", "Sunny", "Cherry", "Peach", "Carrot Cake", "Luffie", "Pascal",
    "Blossom", "Buttercup", "Bubbles", "Miri", "Mia", "Lala", "Risa", "Oliver", "Butterball",
    "Theo", "Calvin", "Simon", "Alvin", "Mittens", "Mr. Cat", "Snowball", "Leo", "Jeffrey",
    "Jada", "Janice", "Kat", "Alfred", "Chase", "Missile Launcher", "Lumos", "Nox", "Kadabra",
    "Cadbury", "Hershey", "Bear", "Chonk", "Boots", "Catbeard the Pirate Cat", "Dog", "Cecelia",
    "Zippy", "Thumbtack", "Snaps", "Velcro", "Miao", "Moogie", "Fish", "Chip", "Salsa", "Ritz",
    "Oreo", "Cheetoh", "Tiger", "Noodle", "Waffle", "Pixel", "Kit-Kat", "Gretchen", "Opal", "Petunia",
    "Lucy", "Eunice", "Gertie", "Marguerite", "Zelda", "Lena", "Maria", "Sophia", "Madame", "Mister",
    "Bruschetta", "Turkey", "Winky", "Socks", "Irene", "Gizmo", "Henry", "Charlie", "Lily",
    "Tinker", "Bell", "Puzzle", "Juice", "Sauce", "Roxanne", "Ilya", "Sakura", "Mian", "Luna",
    "Scout", "Toby", "Lychee", "Boba", "Moss", "Handkerchief", "Gnocchi", "Dia", "Porcini", "Romeo",
    "Rocky", "Olive", "Pumpkin", "Pepper", "Jean", "Miso", "Jiji"]